when:
  branch:
    exclude: [ pages ]

steps:
  build:
    image: alpine:3.19
    commands:
      - apk add hugo
      - hugo --minify
    when:
      event: [ pull_request, push ]

  publish:
    image: bitnami/git
    environment:
      MAIL:
        from_secret: mail
      CODEBERG_TOKEN:
        from_secret: codeberg_token
      HUGO_OUTPUT: public
    commands:
      - git config --global user.email "$MAIL"
      - git config --global user.name "Woodpecker CI"
      - git clone -b pages https://"$CODEBERG_TOKEN"@codeberg.org/$CI_REPO.git $CI_REPO_NAME
      - cp -ar $HUGO_OUTPUT/. $CI_REPO_NAME/
      - cp .domains $CI_REPO_NAME || true
      - cd $CI_REPO_NAME
      - git add .
      - git commit -m "Woodpecker CI ${CI_BUILD_CREATED}"
      - git push
    when:
      event: push