baseURL = "https://tom79.dev/"
languageCode = "en"
title = "tom79"

[params]
  description = "Open source apps for the Fediverse"
  author = "tom79"

[outputs]
  home = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"

[menus]
  [[menus.main]]
    name = "Projects"
    url = "/apps/"
    weight = 10
  [[menus.main]]
    name = "Support"
    url = "/support/"
    weight = 25
  [[menus.main]]
    name = "About"
    url = "/about/"
    weight = 30
